spring:
  application:
    name: ConfigServerService
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.1.70:8761/eureka}
  instance:
    preferIpAddress: false